# Generated by Django 3.1.7 on 2021-03-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('driving', 'driving'), ('stopping', 'stopping')], max_length=255)),
                ('port', models.CharField(choices=[('Oulu', 'Oulu'), ('Kokkola', 'Kokkola'), ('Vaasa', 'Vaasa'), ('Pori', 'Pori'), ('Aland', 'Aland'), ('Turku', 'Turku'), ('Helsinki', 'Helsinki'), ('Hamina', 'Hamina')], max_length=255)),
            ],
        ),
    ]
