# Generated by Django 3.1.7 on 2021-03-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='end',
            field=models.CharField(choices=[('Oulu', 'Oulu'), ('Kokkola', 'Kokkola'), ('Vaasa', 'Vaasa'), ('Pori', 'Pori'), ('Aland', 'Aland'), ('Turku', 'Turku'), ('Helsinki', 'Helsinki'), ('Hamina', 'Hamina')], max_length=255),
        ),
        migrations.AlterField(
            model_name='guide',
            name='start',
            field=models.CharField(choices=[('Oulu', 'Oulu'), ('Kokkola', 'Kokkola'), ('Vaasa', 'Vaasa'), ('Pori', 'Pori'), ('Aland', 'Aland'), ('Turku', 'Turku'), ('Helsinki', 'Helsinki'), ('Hamina', 'Hamina')], max_length=255),
        ),
    ]
